# fly.toml app configuration file generated for morocco-nig on 2024-04-14T06:35:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morocco-nig"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
